// <auto-generated />
namespace UNETI.FIT.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fit2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fit2));
        
        string IMigrationMetadata.Id
        {
            get { return "201505120007057_fit2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
