// <auto-generated />
namespace UNETI.FIT.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class uneti : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uneti));
        
        string IMigrationMetadata.Id
        {
            get { return "201503300211090_uneti"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
