//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UNETI.FIT.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ sở Hà Nội : 456 - Minh Khai, Hà Nội.
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ sở Nam Định : 353 - Trần Hưng Đạo, Nam Định.
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admissions.
        /// </summary>
        public static string Admissions {
            get {
                return ResourceManager.GetString("Admissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement.
        /// </summary>
        public static string Announcement {
            get {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Manager.
        /// </summary>
        public static string ArticleManager {
            get {
                return ResourceManager.GetString("ArticleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Manager.
        /// </summary>
        public static string CategoryManager {
            get {
                return ResourceManager.GetString("CategoryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ClassOfStudy {
            get {
                return ResourceManager.GetString("ClassOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create at.
        /// </summary>
        public static string CreateAt {
            get {
                return ResourceManager.GetString("CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new category.
        /// </summary>
        public static string CreateNewCategory {
            get {
                return ResourceManager.GetString("CreateNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new module.
        /// </summary>
        public static string CreateNewModule {
            get {
                return ResourceManager.GetString("CreateNewModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new news.
        /// </summary>
        public static string CreateNewNews {
            get {
                return ResourceManager.GetString("CreateNewNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new student.
        /// </summary>
        public static string CreateNewStudent {
            get {
                return ResourceManager.GetString("CreateNewStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new subject.
        /// </summary>
        public static string CreateNewSubject {
            get {
                return ResourceManager.GetString("CreateNewSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new teacher.
        /// </summary>
        public static string CreateNewTeacher {
            get {
                return ResourceManager.GetString("CreateNewTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteSubject {
            get {
                return ResourceManager.GetString("DeleteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditSubject {
            get {
                return ResourceManager.GetString("EditSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End at.
        /// </summary>
        public static string EndAt {
            get {
                return ResourceManager.GetString("EndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter keyword....
        /// </summary>
        public static string EnterKeyword {
            get {
                return ResourceManager.GetString("EnterKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string Faculty {
            get {
                return ResourceManager.GetString("Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File manager.
        /// </summary>
        public static string FileManager {
            get {
                return ResourceManager.GetString("FileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty Infomation Technical.
        /// </summary>
        public static string FIT {
            get {
                return ResourceManager.GetString("FIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last page.
        /// </summary>
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of training.
        /// </summary>
        public static string LevelOfTraining {
            get {
                return ResourceManager.GetString("LevelOfTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List category manager.
        /// </summary>
        public static string ListCategoryManager {
            get {
                return ResourceManager.GetString("ListCategoryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List manager.
        /// </summary>
        public static string ListManager {
            get {
                return ResourceManager.GetString("ListManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List module manager.
        /// </summary>
        public static string ListModuleManager {
            get {
                return ResourceManager.GetString("ListModuleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List news manager.
        /// </summary>
        public static string ListNewsManager {
            get {
                return ResourceManager.GetString("ListNewsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of participating students.
        /// </summary>
        public static string ListOfParticipatingStudents {
            get {
                return ResourceManager.GetString("ListOfParticipatingStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of students wating for confimation.
        /// </summary>
        public static string ListOfStudentsWaitingForConfirmation {
            get {
                return ResourceManager.GetString("ListOfStudentsWaitingForConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List subject.
        /// </summary>
        public static string ListOfSubject {
            get {
                return ResourceManager.GetString("ListOfSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List student manager.
        /// </summary>
        public static string ListStudentManager {
            get {
                return ResourceManager.GetString("ListStudentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List subject manager.
        /// </summary>
        public static string ListSubjectManager {
            get {
                return ResourceManager.GetString("ListSubjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List teacher manager.
        /// </summary>
        public static string ListTeacherManager {
            get {
                return ResourceManager.GetString("ListTeacherManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module ID.
        /// </summary>
        public static string ModuleID {
            get {
                return ResourceManager.GetString("ModuleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module manager.
        /// </summary>
        public static string ModuleManager {
            get {
                return ResourceManager.GetString("ModuleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most news.
        /// </summary>
        public static string MostNew {
            get {
                return ResourceManager.GetString("MostNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most register.
        /// </summary>
        public static string MostRegister {
            get {
                return ResourceManager.GetString("MostRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most view.
        /// </summary>
        public static string MostView {
            get {
                return ResourceManager.GetString("MostView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News manager.
        /// </summary>
        public static string NewsManager {
            get {
                return ResourceManager.GetString("NewsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olympic IT.
        /// </summary>
        public static string OPL {
            get {
                return ResourceManager.GetString("OPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other feature.
        /// </summary>
        public static string OtherFeature {
            get {
                return ResourceManager.GetString("OtherFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice.
        /// </summary>
        public static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register student.
        /// </summary>
        public static string RegisteredStudent {
            get {
                return ResourceManager.GetString("RegisteredStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulation.
        /// </summary>
        public static string Regulation {
            get {
                return ResourceManager.GetString("Regulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report the progress.
        /// </summary>
        public static string ReportProgress {
            get {
                return ResourceManager.GetString("ReportProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require.
        /// </summary>
        public static string Require {
            get {
                return ResourceManager.GetString("Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research.
        /// </summary>
        public static string Research {
            get {
                return ResourceManager.GetString("Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at.
        /// </summary>
        public static string StartAt {
            get {
                return ResourceManager.GetString("StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical reports.
        /// </summary>
        public static string StatisticalReports {
            get {
                return ResourceManager.GetString("StatisticalReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        public static string StudentID {
            get {
                return ResourceManager.GetString("StudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student manager.
        /// </summary>
        public static string StudentManager {
            get {
                return ResourceManager.GetString("StudentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study program.
        /// </summary>
        public static string StudyProgram {
            get {
                return ResourceManager.GetString("StudyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study time.
        /// </summary>
        public static string StudyTime {
            get {
                return ResourceManager.GetString("StudyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject manager.
        /// </summary>
        public static string SubjectManager {
            get {
                return ResourceManager.GetString("SubjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a Subject.
        /// </summary>
        public static string SubjectRegister {
            get {
                return ResourceManager.GetString("SubjectRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag manager.
        /// </summary>
        public static string TagManager {
            get {
                return ResourceManager.GetString("TagManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher ID.
        /// </summary>
        public static string TeacherID {
            get {
                return ResourceManager.GetString("TeacherID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher manager.
        /// </summary>
        public static string TeacherManager {
            get {
                return ResourceManager.GetString("TeacherManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        public static string Thumbnail {
            get {
                return ResourceManager.GetString("Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string TopSubject {
            get {
                return ResourceManager.GetString("TopSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total joined students.
        /// </summary>
        public static string TotalJoinedStudents {
            get {
                return ResourceManager.GetString("TotalJoinedStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total module.
        /// </summary>
        public static string TotalModule {
            get {
                return ResourceManager.GetString("TotalModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade union.
        /// </summary>
        public static string TradeUnion {
            get {
                return ResourceManager.GetString("TradeUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University of Economic and Technical Industries.
        /// </summary>
        public static string UNETI {
            get {
                return ResourceManager.GetString("UNETI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update at.
        /// </summary>
        public static string UpdateAt {
            get {
                return ResourceManager.GetString("UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a subject.
        /// </summary>
        public static string UploadSubject {
            get {
                return ResourceManager.GetString("UploadSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View more.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth.
        /// </summary>
        public static string Youth {
            get {
                return ResourceManager.GetString("Youth", resourceCulture);
            }
        }
    }
}
